In [1]:
from google.colab import files
uploaded = files.upload()

Saving Cleaned_Dataset.xlsx to Cleaned_Dataset.xlsx

In [4]:
import pandas as pd
import sqlite3

In [3]:
file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)

In [5]:
conn = sqlite3.connect(':memory:')

In [6]:
df.to_sql('sales_data', conn, index=False,
          if_exists='replace')
print("Database Created Successfully")

Database Created Successfully

In [7]:
query = "SELECT * FROM sales_data"
result = pd.read_sql(query, conn)
result.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [9]:
query = """
SELECT Product, TotalPrice
FROM sales_data
"""
result = pd.read_sql(query, conn)
result.head()

   Product  TotalPrice
0  Monitor     2853.10
1    Phone      302.70
2   Tablet     2753.40
3    Chair      273.19
4  Printer     2504.04

In [15]:
print(f"Maximum TotalPrice in DataFrame: {df['TotalPrice'].max()}")
query = """
SELECT *
FROM sales_data
WHERE TotalPrice > 3000
"""
result = pd.read_sql(query, conn)
result.head()

Maximum TotalPrice in DataFrame: 3456.4

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200010,2023-12-29 00:00:00,C43443,Tablet,5,625.97,333 Main St,Credit Card,Returned,TRK98859248,9,WINTER15,Instagram,3129.85
1,ORD200086,2024-06-19 00:00:00,C88205,Printer,5,643.03,447 Main St,Online,Cancelled,TRK93504166,5,FREESHIP,Referral,3215.15
2,ORD200097,2025-01-21 00:00:00,C15624,Tablet,5,619.52,922 Main St,Debit Card,Pending,TRK40621141,9,No Coupon,Email,3097.60
3,ORD200107,2023-03-27 00:00:00,C16775,Printer,5,670.75,848 Main St,Gift Card,Shipped,TRK34392124,8,FREESHIP,Instagram,3353.75
4,ORD200221,2024-02-23 00:00:00,C93473,Tablet,5,639.37,552 Main St,Debit Card,Pending,TRK50003989,6,SAVE10,Google,3196.85

In [17]:
query = """
SELECT Product, TotalPrice
FROM sales_data
ORDER BY TotalPrice DESC
"""
result = pd.read_sql(query, conn)
result.head()

   Product  TotalPrice
0   Tablet     3456.40
1  Monitor     3390.95
2   Laptop     3390.80
3    Chair     3384.90
4   Tablet     3370.20

In [18]:
query = """
SELECT PaymentMethod, COUNT(*) as Total_Orders
FROM sales_data
GROUP BY PaymentMethod
"""
result = pd.read_sql(query, conn)
result

  PaymentMethod  Total_Orders
0          Cash           246
1   Credit Card           234
2    Debit Card           232
3     Gift Card           230
4        Online           258

In [21]:
query = """
SELECT SUM(TotalPrice) as Total_Revenue
FROM sales_data
"""
result = pd.read_sql(query, conn)
result

   Total_Revenue
0     1264761.96

In [20]:
query = """
SELECT AVG(TotalPrice) as Average_Price
FROM sales_data
"""
result = pd.read_sql(query, conn)
result

   Average_Price
0      1053.9683